# Generated by Django 5.2.6 on 2026-04-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Max time to first response in minutes')),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Max time to resolution in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portal_sla_policy',
                'unique_together': {('tenant_id', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('BREACHED', 'Breached')], default='PENDING', max_length=10)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('BREACHED', 'Breached')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackings', to='portal.slapolicy')),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='portal.ticket')),
            ],
            options={
                'db_table': 'portal_sla_tracking',
            },
        ),
    ]
