# Generated by Django 5.2.6 on 2026-04-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_slapolicy_slatracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='csat_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='duplicate_of',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='linked_bug_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='linked_feature_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment_score',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('FRUSTRATED', 'Frustrated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'Low — minor inconvenience'), ('MEDIUM', 'Medium — workaround exists'), ('HIGH', 'High — significantly impacted'), ('CRITICAL', 'Critical — completely blocked')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'Portal'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], default='PORTAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('BUG', 'Bug Report'), ('FEATURE_REQUEST', 'Feature Request'), ('QUESTION', 'Question'), ('ONBOARDING_ISSUE', 'Onboarding Issue'), ('INTEGRATION_ISSUE', 'Integration Issue'), ('PERFORMANCE_ISSUE', 'Performance Issue'), ('SUPPORT', 'Support'), ('BILLING', 'Billing'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('PENDING_CLIENT', 'Pending Client'), ('PENDING_RELEASE', 'Pending Release'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='NEW', max_length=20),
        ),
    ]
