# Generated by Django 5.2.6 on 2026-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_enhance_ticket_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('PENDING_CLIENT', 'Pending Client'), ('PENDING_RELEASE', 'Pending Release'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='OPEN', max_length=20),
        ),
    ]
