# Generated by Django 5.2.6 on 2026-04-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('PLANNED', 'Planned'), ('IN_DEV', 'In Development'), ('IN_QA', 'In QA'), ('IN_STAGING', 'In Staging'), ('RELEASED', 'Released'), ('DECLINED', 'Declined')], default='BACKLOG', max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=5, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_release', models.DateField(blank=True, null=True)),
                ('actual_release', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_feature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('assigned_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('health_score', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('BLOCKED', 'Blocked')], default='ON_TRACK', max_length=20)),
                ('estimated_go_live', models.DateField(blank=True, null=True)),
                ('actual_go_live', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_onboarding_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TESTING', 'In Testing'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('is_hotfix', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_release',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('ON_ROADMAP', 'On Roadmap'), ('DECLINED', 'Declined'), ('RELEASED', 'Released')], default='UNDER_REVIEW', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('linked_ticket_id', models.IntegerField(blank=True, null=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='delivery.feature')),
            ],
            options={
                'db_table': 'delivery_feature_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='NOT_STARTED', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='delivery.onboardingproject')),
            ],
            options={
                'db_table': 'delivery_onboarding_phase',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(choices=[('CLIENT', 'Client'), ('DELIVERY', 'Delivery Team')], default='DELIVERY', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocker', models.BooleanField(default=False)),
                ('blocker_reason', models.TextField(blank=True, null=True)),
                ('linked_ticket_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.onboardingphase')),
            ],
            options={
                'db_table': 'delivery_onboarding_task',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='linked_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='delivery.release'),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('REPRODUCED', 'Reproduced'), ('ROOT_CAUSE_IDENTIFIED', 'Root Cause Identified'), ('FIX_IN_PROGRESS', 'Fix In Progress'), ('IN_QA', 'In QA'), ('DEPLOYED', 'Deployed'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], default='REPORTED', max_length=30)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('affected_tenants', models.JSONField(blank=True, default=list)),
                ('client_impact', models.TextField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('fix_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('linked_ticket_ids', models.JSONField(blank=True, default=list)),
                ('pr_url', models.CharField(blank=True, max_length=500, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='delivery.release')),
            ],
            options={
                'db_table': 'delivery_bug',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='delivery.feature')),
            ],
            options={
                'db_table': 'delivery_feature_vote',
                'unique_together': {('feature', 'user_email')},
            },
        ),
    ]
