# Generated by Django 5.2.6 on 2026-04-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CLIENT_ADMIN', 'Client Admin'), ('CLIENT_USER', 'Client User'), ('AGENT', 'Agent'), ('LEAD', 'Lead'), ('ADMIN', 'Admin')], max_length=20)),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_permissions', models.JSONField(blank=True, default=list)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'um_user_profile',
                'ordering': ['user_name'],
            },
        ),
    ]
