"""
Django settings for customer_portal project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import datetime
import os
import logging.config
from django.utils.log import DEFAULT_LOGGING
import logging
from pathlib import Path
logger = logging.getLogger(__name__)
BASE_DIR = os.getenv('baseLogsDir', Path(__file__).resolve().parent.parent)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("secretKey",'qa-django-insecure-@%movk#(x8jkoq7=8!6map!y(d5)zn4k-xmk_%q8bye+81-0t3')
DATE_FORMAT = "%Y-%m-%d"

# Valid Response Codes
VALID_RESPONSE_CODES = [200, 201, 204]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'customer_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'customer_portal.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'customer_portal',
        'USER': 'akash.kumar',
        'PASSWORD': 'India%40123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = False

# Disable Django's logging setup
LOGGING_CONFIG = None
LOGLEVEL = os.getenv('logLevel', 'info').upper()
SERVICE_NAME = 'CUSTOMER-PORTAL'
LOGS_FOLDER = 'logs'
LOGS_FOLDER_PATH = os.path.join(BASE_DIR, LOGS_FOLDER)

# Check if the logs folder exists, if not, create it
if not os.path.exists(LOGS_FOLDER_PATH):
    os.makedirs(LOGS_FOLDER_PATH, exist_ok=True)

# Define the logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            # exact format is not important, this is the minimum information
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
        'standard': {
            'format' : "[%(asctime)s] %(levelname)s"+ f" {SERVICE_NAME} " +"[%(name)s:%(lineno)s] %(message)s",
            #'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'django.server': DEFAULT_LOGGING['formatters']['django.server'],
    },
    'handlers': {
        # console logs to stderr
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            },
        'log_file_handler': {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{os.path.join(LOGS_FOLDER_PATH, datetime.now().date().strftime('%Y-%m-%d'))}.log",
            "mode": "a",
            "encoding": "utf-8",
            "formatter": "standard",
            "level": "DEBUG",
            "backupCount": 10,
            "maxBytes":  50*1024*1024,  # 50 MB
            'delay': True,  # Add delay to handle permission errors
            },

        'django.server': DEFAULT_LOGGING['handlers']['django.server'],
    },
    'loggers': {
        # default for all undefined Python modules
        '': {
            'level': 'WARNING',
            'handlers': ['console', 'log_file_handler'],
        },
        # Our application code
        'app': {
            'level': LOGLEVEL,
            'handlers': ['console', 'log_file_handler'],
            'propagate': False,     # Prevent propagation to higher-level(double logging because of root logger) loggers
        },
        # Default runserver request logging
        'django.server': DEFAULT_LOGGING['loggers']['django.server'],
    },
}

# Apply the logging configuration
logging.config.dictConfig(LOGGING)

#CELERY CONFIG
# RMQ_USER = os.environ.get("RABBITMQ_DEFAULT_USER")
# RMQ_PASSWORD = os.environ.get("RABBITMQ_DEFAULT_PASS")
# RABBITMQ_URL = os.environ.get("RABBITMQ_URL")
#CELERY CONFIG
# CELERY_MAX_QUEUES_PER_WORKER=os.environ.get("CELERY_MAX_QUEUES_PER_WORKER")
# CELERY_MAX_PARALLEL_TASKS_PER_WORKER=os.environ.get("CELERY_MAX_PARALLEL_TASKS_PER_WORKER")
# CELERY_BROKER_URL = f"amqp://{RMQ_USER}:{RMQ_PASSWORD}@rabbitmq/rabbitmq"
# CELERY_RESULT_BACKEND = "rpc://"
# CELERY_TASK_DEFAULT_QUEUE = "dpai_service_default_queue"